### ISSUE TITLE
Interop has adopted Credential Exchange flow

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/interoperability#15]
With AuthN Adopted, it is now time to discucss credential exchange / delivery.

There are Agents and Hubs, as well as HTTP, Identity Wallets, all will have opinion about how they would like to receive credentials.

Lets continue the discussion regarding DIDComm and Agent / Hub Integration.

Please comment a completed end to end example of how you think this can work, with links to supporting documentation.

**Comment by OR13** [comment]
Worst case scenario, we can provide a custom http interface that takes id_tokens and returns credentilals / presentations in JSON format.

GET & POST

```
/credential/:id
/presentation/:id
```

A user can only add or get credentials if they are the issue for the subject, id_token will be used for Authorization Header.

**Comment by dhh1128** [comment]
The credential exchange should be accomplished using this DIDComm protocol: https://github.com/hyperledger/aries-rfcs/blob/master/features/0037-present-proof/README.md. This protocol supports JWT-based credentials, and it can run over http(s). Plus it already has some implementations.

**Comment by OR13** [comment]
awesome, can we add links for any implementations and describe the flow with 2 different DID Methods?

Issuer : did:btcr:xxcl-lzpq-q83a-0d5 holds <proofOfEducationCredential>

Subject: did:sov:WRfXPg8dantKVubE3HX8pw wants <proofOfEducationCredential>

Per the RFC it looks like there are some [negotiation messages](https://github.com/hyperledger/aries-rfcs/blob/master/features/0037-present-proof/README.md#negotiation-and-preview) which need to be sent

I imagine these messages are sent by agents, which much be listed in serviceEndpoints.

Can we add a reference to the agent code that can support (or will soon support) this functionality?

I believe this library would support creating of the messages: https://github.com/decentralized-identity/DIDComm-js

If thats the case, we just need to know how to send them to the agents.
