### ISSUE TITLE
Interop project has documented Agent / Hub Support

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/interoperability#17]
In order for a Hub or Agent implementation to be supported, a document must be contributed to this repo describing how to leverage the Hub / Agent with at least 2 different DID Methods.

All code necessary to complete the linking should be included, such as protocol messages, public web service endpoints, authentication details, etc.

**Comment by csuwildcat** [comment]
@codeglobally tagging you in for visibility into the community's request/needs

**Comment by OR13** [comment]
Specifically, we should focus on support for Write / Read.

**Comment by OR13** [comment]
Issuer Agent Creates Credential, Transfers it Subject Hub, Verifier can request Credential from Subject Hub.

**Comment by OR13** [comment]
@TelegramSam to add RFC / code links. May be a good opportunity to develop an "Aries implementers Guide".

**Comment by TelegramSam** [comment]
Links, per our call yesterday:

The best collection of DID Comm related info is in the Reference Section of RFC 0005: https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0005-didcomm/README.md#reference
In particular to our discussion, Message Types, Message Anatomy, and Agent Transports.

Code to connect a webserver to an Aries agent: https://github.com/hyperledger/aries-staticagent-python
The examples folder has relevant webserver examples.
