### ISSUE TITLE
Adopt Development Dependencies

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/interoperability#8]
In order to provide the proper level of modularity, and support easy contribution, I'm recommending the following project structure.

0. JavaScript (not TS or Coffee)
1. Lerna Mono Repo https://github.com/lerna/lerna
2. Travis CI 
3. CodeCov
4. Github Pages for Documentation
5. Docker Support For Development Environment

More controversial:

- React/SPA for Verifier + Issuer Web Sites
- Storybook for UI Components
- Express JS for Web Server

**Comment by csuwildcat** [comment]
My only question would be, do we really need React for this, vs something simpler, like Web Components and a component/data handling lib. Might give Lit HTML a look: https://www.polymer-project.org/blog/2019-02-05-lit-element-and-lit-html-release

**Comment by OR13** [comment]
we of course do not need react / angular / vue.

We can use vanilla JS and no Webpack or rollup.

As soon as we decide to use Webpack / rollup or node_modules for dependencies, it starts to become nice to pick a framework like react / angular vue.

But we can keep the UI separate from business logic, and indeed if we want to show support for all 3 I believe we could.

I'm most familiar with React at this point, and since React Native is popular on mobile, I thought it would make for a good compromise.

**Comment by OR13** [comment]
These where just suggestions.
